--create database db_tapserve
--use db_tapserve

CREATE TABLE ROLE(
ID VARCHAR(36) PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION TEXT
); 

CREATE TABLE CAPABILITY(
ID VARCHAR(36) PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION TEXT,
ROLE_ID VARCHAR(36) NOT NULL,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
); 

CREATE TABLE USER(
ID VARCHAR(36) PRIMARY KEY,
ROLE_ID VARCHAR(36) NOT NULL,
NAME VARCHAR(200) NOT NULL,
ADDRESS TEXT NOT NULL,
CONTACT_NUMBER BIGINT NOT NULL,
FB_ID BIGINT UNIQUE,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
); 

CREATE TABLE ADMINISTRATOR(
ID VARCHAR(36) PRIMARY KEY,
ROLE_ID VARCHAR(36) NOT NULL,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION TEXT,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
); 

CREATE TABLE SERVICE_PROVIDER(
ID VARCHAR(36) PRIMARY KEY,
ROLE_ID VARCHAR(36) NOT NULL,
NAME VARCHAR(200) NOT NULL,
ORGANIZATION_NAME VARCHAR(200),
PHOTO BLOB,
CONTACT_NUMBER BIGINT NOT NULL,
ADDRESS TEXT NOT NULL,
REGION_ID VARCHAR(200) NOT NULL,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
); 

CREATE TABLE FRIEND_LIST(
ID VARCHAR(36) PRIMARY KEY,
USER_ID VARCHAR(36) NOT NULL,
FRIEND_ID BIGINT NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER(ID)
); 

CREATE TABLE SERVICE(
ID VARCHAR(36) PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION TEXT
); 

CREATE TABLE SERVICE_TO_PROVIDER_MAPPER(
ID VARCHAR(36) PRIMARY KEY,
SERVICE_PROVIDER_ID VARCHAR(36) NOT NULL,
SERVICE_ID VARCHAR(36) NOT NULL,
FOREIGN KEY(SERVICE_PROVIDER_ID) REFERENCES SERVICE_PROVIDER(ID),
FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(ID)
); 

CREATE TABLE RATING_REVIEW(
ID VARCHAR(36) PRIMARY KEY,
RATING INT,
REVIEW TEXT,
USER_ID VARCHAR(36) NOT NULL,
SERVICE_PROVIER_ID VARCHAR(36) NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER(ID),
FOREIGN KEY(SERVICE_PROVIER_ID) REFERENCES SERVICE_PROVIDER(ID)
); 

CREATE TABLE APPOINTMENT(
ID VARCHAR(36) PRIMARY KEY,
NAME VARCHAR(200),
DESCRIPTION TEXT,
USER_ID VARCHAR(36) NOT NULL,
SERVICE_PROVIER_ID VARCHAR(36) NOT NULL,
SERVICE_ID VARCHAR(36) NOT NULL,
ADDRESS TEXT NOT NULL,
BOOKING_DATE DATETIME NOT NULL,
APPOINTMENT_DATE DATETIME NOT NULL,
STATUS INT NOT NULL,
CONTACT_NUMBER BIGINT NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER(ID),
FOREIGN KEY(SERVICE_PROVIER_ID) REFERENCES SERVICE_PROVIDER(ID),
FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(ID)
); 

CREATE TABLE PAYMENT(
ID VARCHAR(36) PRIMARY KEY,
APPOINTMENT_ID VARCHAR(36) NOT NULL,
AMOUNT NUMERIC NOT NULL,
MODE VARCHAR(200),
STATUS INT NOT NULL,
FOREIGN KEY(APPOINTMENT_ID) REFERENCES APPOINTMENT(ID)
); 

CREATE TABLE CREDENTIALS(
ID VARCHAR(36) PRIMARY KEY,
USERNAME VARCHAR(200) UNIQUE NOT NULL ,
PASSWORD VARCHAR(200) NOT NULL ,
ACTOR_ID VARCHAR(36)
);
